### ISSUE TITLE
DynamoDB retry handler

### ISSUE THREAD

**Issue by nhibberd** [brendanhay/amazonka#351] opened 2017-01-17 01:30 UTC
Seeing the following exception:
```
 [ServiceError] {
   service    = DynamoDB
   status     = 400 Bad Request
   code       = ProvisionedThroughputExceeded
   message    = Just The level of configured provisioned throughput for the table was exceeded. Consider increasing your provisioning level with the UpdateTable API.
 }
```

Seems that all of the generated retry handlers are expecting `ProvisionedThroughputExceededException` which matches the [amazon documentation](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html) whereas the error I'm seeing is `ProvisionedThroughputExceeded`. Have manually configured the retry handlers with that new value and everything works nicely as expected

**Comment by brendanhay** [comment] 2017-01-17 01:47
Thanks for bringing it to my attention. I'll dig through the upstream changes and possibly re-raise or correct.

**Comment by MHova** [comment] 2017-06-15 01:25
Any progress on this issue?

**Comment by endgame** [comment] 2021-05-10 22:34
Despite the regenerated amazonka-dynamodb only having a constant for `ProvisionedThroughputExceeded`

https://github.com/brendanhay/amazonka/blob/b0c76968be1f9f36927494c25ebfdedfd5981893/amazonka-dynamodb/gen/Network/AWS/DynamoDB/Types/BatchStatementErrorCodeEnum.hs#L83-L84

It still appears to be checking for `ProvisionedThroughputExceededException` in the retry check:

https://github.com/brendanhay/amazonka/blob/b0c76968be1f9f36927494c25ebfdedfd5981893/amazonka-dynamodb/gen/Network/AWS/DynamoDB/Types.hs#L1045-L1051

**Comment by endgame** [comment] 2021-10-02 08:26
Okay, I did some digging. The `ProvisionedThroughputExceeded` enum is defined in botocore:

https://github.com/boto/botocore/blob/6155f328adb44bc33c7bb2a9c85ce695a48be133/botocore/data/dynamodb/2012-08-10/service-2.json#L1399-L1413

If you backtrace this through the service definitions, you find that this enum is only declared to be part of the response element of a [`BatchExecuteStatement`](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchExecuteStatement.html) call, which applies a batch of PartiQL statements. This appears to be [correctly documented in the `BatchStatementError` docs](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchStatementError.html#DDB-Type-BatchStatementError-Code).

I checked the python, go, and java SDKs and I can find no wrangling between a `ProvisionedThroughputExceeded` code and `ProvisionedThroughputExceededException`.

I'd be surprised to see the service definition, a [test case in botocore](https://github.com/boto/botocore/blob/develop/tests/unit/response_parsing/json/errors/dynamodb-put-item.json) and three AWS SDKs all being wrong. There's also a [StackOverflow question](https://stackoverflow.com/questions/29101371/getting-provisionedthroughputexceededexception-error-when-iterating-over-dynamod) that shows the exception being thrown in actual code (and I couldn't find custom wrangling for the error code in botocore).

I'm closing this as "not a bug - user error due to confusing types in the service definition". However @nhibberd 's comment that he was able to tweak retry values and make things go gives me a small nagging doubt, so if anyone wants to provide a reproduction case and reopen this issue, be my guest..

**Closed by endgame** 2021-10-02 08:26 UTC
Labels: needs triage
