### ISSUE TITLE
Building amazonka-swf on ghc-8.8.1 takes too much memory

### ISSUE THREAD

**Issue by newhoggy** [brendanhay/amazonka#550] opened 2019-10-07 07:35 UTC
More details here:

https://gitlab.haskell.org/ghc/ghc/issues/17317

**Comment by turboMaCk** [comment] 2020-06-30 13:43
I'm experiencing similar behavior on ghc 8.8.3 as well.

**Comment by rossabaker** [comment] 2020-07-01 14:31
I have something in our internal fork that splits up the Types modules, and it makes a huge difference on amazonka-ec2.  I'm fixing some fallout on the updated modules, but intend to have a PR soon.

**Comment by endgame** [comment] 2021-09-27 11:40
Closing as dupe of #549 , which has more detailed comments of things we might be able to do.

**Closed by endgame** 2021-09-27 11:40 UTC
Labels: needs triage
