### ISSUE TITLE
Failure parsing ObjectStorageClass from value: 'intelligent_tiering'. Accepted values: glacier, reduced_redundancy, standard, standard_ia"

### ISSUE THREAD

**Issue by k-bx** [brendanhay/amazonka#569] opened 2020-03-24 20:21 UTC
Got it while trying to list the common crawl news bucket `s3://commoncrawl/crawl-data/CC-NEWS/2020/03/`: `Failure parsing ObjectStorageClass from value: 'intelligent_tiering'. Accepted values: glacier, reduced_redundancy, standard, standard_ia"`

I guess we need to add the intelligent_tiering somewhere.

**Comment by dustin** [comment] 2021-01-09 05:43
Also, `onezone_ia`

    Failure parsing ObjectStorageClass from value: 'onezone_ia'. Accepted values: glacier, reduced_redundancy, standard, standard_ia"})

**Comment by endgame** [comment] 2021-09-27 11:28
Closing as dupe of #609

**Closed by endgame** 2021-09-27 11:28 UTC
Labels: needs triage
