### ISSUE TITLE
Lambda - invoke as event, no return data to deserialize results in error

### ISSUE THREAD

**Issue by andrevdm** [brendanhay/amazonka#407] opened 2017-09-23 20:16 UTC
When a lambda is invoked as an event (or DryRun) there is no data in the response body. Aeson then gets an empty string and fails with a SerializeError

E.g.
```
[Raw Response Body] {

}
[SerializeError] {
  service = Lambda
  status  = 202 Accepted
  message = Error in $: not enough input
  body    = Just 
}
aws01: SerializeError (SerializeError' {_serializeAbbrev = Abbrev "Lambda", _serializeStatus = Status {statusCode = 202, statusMessage = "Accepted"}, _serializeBody = Just "", _serializeMessage = "Error in $: not enough input"})
```

An AWSRequest instance like this avoids the issue

```
instance AWSRequest Invoke where
        type Rs Invoke = InvokeResponse
        request = postBody lambda
        response =
           (deserialise bodyDecode')
              (\ s h x ->
                 InvokeResponse' <$>
                   (h .#? "X-Amz-Function-Error") <*>
                     (h .#? "X-Amz-Log-Result")
                     <*> (pure (Just x))
                     <*> (pure (fromEnum s)))

          where
            bodyDecode' :: LazyByteString -> Either [Char] (HashMap Text Value)
            bodyDecode' bs =
              if bs == ""
              then Right $ Map.empty
              else eitherDecode' bs

```

**Comment by utdemir** [comment] 2018-04-29 21:31
I think this is a duplicate of #394 .

**Comment by brendanhay** [comment] 2018-05-14 10:51
Closing as duplicate of #394

**Closed by brendanhay** 2018-05-14 10:51 UTC
