### ISSUE TITLE
amazonka-secretsmanager is not registered in stackage

### ISSUE THREAD

**Issue by ncaq** [brendanhay/amazonka#978] opened 2024-02-28 08:46 UTC
I see [stackage/build-constraints.yaml at master · commercialhaskell/stackage](https://github.com/commercialhaskell/stackage/blob/master/build-constraints.yaml),
amazonka-secretsmanager is not written to the stackage,
so extra-deps is required even in the latest stackage.

**Comment by endgame** [comment] 2024-02-28 09:58
Dupe of #969

**Closed by endgame** 2024-02-28 09:58 UTC

**Comment by ncaq** [comment] 2024-02-29 03:45
My apologies.
I thought you had simply forgotten to write it because it was not written, rather than commented out with a reason for blocking.

**Comment by endgame** [comment] 2024-02-29 05:58
No problem. I need to get a bunch of hackage bounds updated so that we clearly communicate that we're not yet GHC 9.8-ready, and then get enough stuff done that it's worth uploading ~300 packages to Hackage. Once that's done, I suppose that stackage will pick amazonka back up again.

**Comment by ysangkok** [comment] 2024-06-19 16:14
I reported

* https://github.com/commercialhaskell/lts-haskell/issues/381
