### ISSUE TITLE
SerializeError - Failure parsing InstanceType from value

### ISSUE THREAD

**Issue by Cmdv** [brendanhay/amazonka#664] opened 2021-10-05 09:28 UTC
I keep getting parsing error when ever I use this function:

```Haskell
import qualified Network.AWS.EC2         as EC2

myFunc = do
  awsEnv <- newEnv Discover
  ips <- runResourceT . runAWS awsEnv $ getEC2InstancesPublicIPs listOfInstanceIDs
  return ips

...

getEC2InstancesPublicIPs :: MonadAWS m => [Text] -> m [Text]
getEC2InstancesPublicIPs instanceIDs = do
  descInstanceResp <- send $ EC2.describeInstances & EC2.diiInstanceIds .~ instanceIDs
  let reservations = descInstanceResp ^. EC2.dirsReservations
      fullInstanceInfos = Prelude.concat $ (^. EC2.rInstances) <$> reservations
      publicIPs = (^. EC2.insPublicIPAddress) <$> fullInstanceInfos
  return $ catMaybes publicIPs
```

> failure parsing InstanceType from value: 'm5a.xlarge'

I've seen issues https://github.com/brendanhay/amazonka/issues/503 + https://github.com/brendanhay/amazonka/issues/460 but can't quite make head/tails as to if there is a solution to get around this parsing error. 

Also it seems that `m5a.xlarge` is present here:
https://github.com/brendanhay/amazonka/blob/27e5fb472139b685244d4fdcc0eba50e04e24b4b/amazonka-ec2/gen/Network/AWS/EC2/Types/InstanceType.hs#L1037-L1038

Any pointers would be greatly appreciated 😄

**Comment by endgame** [comment] 2021-10-05 10:06
Since your code snippet contains old-style lenses, I assume you're still on the 1.6.1 release from Hackage. Unfortunately that version of the package parses instance types into a sum type, which means there's no out if AWS emits new values (as it's done here - that version of `amazonka-ec2` predates the `m5a` instance family).

The current version on `develop` uses `newtype` wrappers instead of sum types, and this allows extra values to be handled without too much grief (though keeping up-to-date is better).

We're working as fast as we can on a 2.0 release candidate, and as part of that process we'll need people to start testing/migrating to it before it hits Hackage. If you want to help (which should get you unstuck as well as help us), you'll need to add a couple of [`source-repository-package` stanzas](https://cabal.readthedocs.io/en/3.4/cabal-project.html#specifying-packages-from-remote-version-control-locations) if using cabal or [`extra-packages`](https://docs.haskellstack.org/en/stable/yaml_configuration/#extra-deps) if using stack. You'll need to remove any dependency on `amazonka-core` (that package no longer exists) and depend only on `amazonka` and `amazonka-ec2`.

I'm going to close this issue because it's not a bug with `amazonka`, but that doesn't mean the conversation is over. Please @ me if you need more detail on the instructions.

**Closed by endgame** 2021-10-05 10:06 UTC

**Comment by Cmdv** [comment] 2021-10-05 12:31
thanks @endgame that's perfect, I'll test out the `develop` branch didn't realise I wasn't on latest as I just pulled down what was on Hackage.

Will report back on how things turn out :)

**Comment by Cmdv** [comment] 2021-10-05 15:33
@endgame sorry to disturb you but could you give me a very quick example of how the new lenses would look like in actions.

Having great difficuties trying to convert old code to new code 🤔
I've tried to look at the tests and the `/examples` folder but can't work it out.

```Haskell
-- | Returns all the IPs of instances.
allVociStatus :: (MonadIO m, MonadCatch (AppT m), MonadUnliftIO (AppT m)) => AppT m [VociStatus]
allVociStatus = do
  -- get the enviroment vars for AWS
  awsEnv <- newEnv Discover
  -- run a query to get scalling groups
  res <- runResourceT . runAWS awsEnv $ do
    -- get the scallinggroups
    resScallingGroup <- send AS.describeAutoScalingGroups
    -- return a list of Maybe auto scalling groups
    let scallingGroups = listToMaybe $ resScallingGroup ^. AS.dasgrsAutoScalingGroups

    case scallingGroups of
      Just asgs -> do
        -- turn the asg into a list of instanceIds
        let instanceIDs = (^. AS.iInstanceId) <$> asgs ^. AS.asgInstances
            validInstance = (^. AS.iInstanceId) <$> asgs ^. AS.asgInstances
        -- run a query to get a list of reservations using instanceIds
        instances <- getEC2InstancesPublicIPs instanceIDs
        return $ Right instances
      Nothing -> do
        return $ Left ""

  logDebugNS "web" (pack $ show res)
  return [voci', voci']

getEC2InstancesPublicIPs :: MonadAWS m => [Text] -> m [Text]
getEC2InstancesPublicIPs instanceIDs = do
  descInstanceResp <- send $ EC2.describeInstances & EC2.diiInstanceIds .~ instanceIDs
  let reservations = descInstanceResp ^. EC2.dirsReservations
      fullInstanceInfos = Prelude.concat $ (^. EC2.rInstances) <$> reservations
      publicIPs = (^. EC2.insPublicIPAddress) <$> fullInstanceInfos
  return $ catMaybes publicIPs

voci' :: VociStatus
voci' = VociStatus {groupName="groupName", statusInfo="some info"}
```
I'm more than happy to update the examples folder if I can have a quick pointer towards even how this would now look:

`resScallingGroup <- send AS.describeAutoScalingGroups`

I worked out that some of the functions have changed from/to:
```Haskell
res <- runResourceT . runAWS awsEnv $ do
  resScallingGroup <- send AS.describeAutoScalingGroups

res <- runResourceT $ do
  resScallingGroup <- send awsEnv AS.describeAutoScalingGroups
```

I do have the added confusion that this is inside a Servant App that has

```
newtype AppT m a = AppT
  { runApp :: ReaderT Config (ExceptT ServerError m) a
  }
  deriving
    ( Functor,
      Applicative,
      Monad,
      MonadReader Config,
      MonadError ServerError,
      MonadIO,
      MonadThrow,
      MonadCatch
    )

-- | MonadUnliftIO instance for @AppT m@
instance  (IU.MonadUnliftIO m, MonadCatch m) => IU.MonadUnliftIO (AppT m) where
  askUnliftIO = AppT $ IU.withUnliftIO $ \u -> pure (IU.UnliftIO (IU.unliftIO u . runApp))

instance (IU.MonadUnliftIO m, Exception e, MonadCatch m) => IU.MonadUnliftIO (ExceptT e m) where
  withRunInIO exceptToIO = ExceptT $
    try $
      IU.withRunInIO $ \runInIO ->
        exceptToIO (runInIO . (either throwIO pure <=< runExceptT))
```
But guessing those will be obsolete or require a `MonadResource` instance of sorts. But happy to work that out myself and isn't realy anything to do with the library it self 😄

**Comment by endgame** [comment] 2021-10-05 21:32
I fixed the examples, so hopefully that helps you. What's the `m` under your `AppT m`? If you're on a custom monad stack, I assume your servant handlers are something like `ServerT (AppT m) a`, and before you serve the entire API you're doing a `hoistServer[withContext?]`?

Note on `MonadResource`/`MonadUnliftIO` - you only need `MonadUnliftIO` to _unwrap_ `ResourceT`, so if it's your innermost transformer you don't have to worry about the (correctly) missing `MonadUnliftIO` instance for `ExceptT`.

You'll need to have a think about where you want to put your `ResourceT`, and it'll depend on how your program runs. If you want to do cleanup once at the end, I'd bake it into `AppT` and unwrap it when you do all the other unwrapping in `hoistServer`. If you want to close all AWS connections within each endpoint handler, I wouldn't bake it into `AppT`. Instead, I'd give `AppT` an `MFunctor` instance from `mmorph` and try something like `hoist runResourceT $ do ...`

You will probably also want to write some wrappers for `send` etc which pull the `Env` from your `ReaderT Config`.

**Comment by endgame** [comment] 2021-10-06 19:36
To use `field @"foo"`, you'll need the extensions `DataKinds` for the type-level string, `TypeApplications` for the `@` operator to work and then whatever else it tells you to turn on (`FlexibleContexts`, I think).

Glad you're unstuck.
