### ISSUE TITLE
Unauthenticated Requests?

### ISSUE THREAD

**Issue by tmspzz** [brendanhay/amazonka#478] opened 2018-07-09 16:19 UTC
Hi, 

how can I make a request to public resources on S3? see https://github.com/blender/Rome/issues/126

I have a dug in the codebase but I could not find any obvious way.

If I catch `MissingFileError` how can I provide all the rest of the environment? 

Also `AccessKey` seems to want a `ByteString` and using `AWS_ACCESS_KEY_ID="" AWS_SECRET_ACCESS_KEY=""` to leads to 400 Bad Reques

```
The authorization header is malformed; a non-empty Access Key (AKID) must be provided in the credential.
```

Thank you very much for this wonderful library.

**Comment by nhibberd** [comment] 2018-07-09 16:59
I would suggest that `AWS_ACCESS_KEY_ID="" AWS_SECRET_ACCESS_KEY=""` is not a good idea.

If the bucket is public why do you need s3 specific download? (public s3 buckets expose a http interface)

**Comment by blender** [comment] 2018-07-09 17:15
Thanks for the reply!

> If the bucket is public why do you need s3 specific download? Could you not access it via the public http interface on the s3 bucket

I was just wondering if for convenience there was an integrate way to to have amazonka do this for me instead of implementing it myself.

**Comment by endgame** [comment] 2021-09-27 12:41
I don't think this is a supported thing right now, and this looks like a dupe of #483 so I'll close it. Maybe after 2.0 comes out we can look at features like this.

**Closed by endgame** 2021-09-27 12:41 UTC
Labels: needs triage
